#!/bin/bash

BRANCH=$(git rev-parse --abbrev-ref HEAD)
REGEX="^(feature|bugfix|doc|dev)\/[0-9]+-(([a-zA-Z]|([a-zA-Z]-[a-zA-Z]))+)$"

if ! [[ $BRANCH =~ $REGEX ]]; then
	echo "Commit rejected due to branching name"
	echo "Rename branch with $REGEX syntax"
	echo "git branch -m"
	exit 1
fi
